# Generated by Django 4.1.7 on 2023-09-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0036_remove_oritem_order_of_payment_delete_orderofpayment_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofpayment',
            name='permit_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ors_1', to='permits.permitapplication'),
        ),
    ]
