# Generated by Django 4.1.7 on 2023-09-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_orderofpayment_permit_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
