# Generated by Django 4.1.7 on 2023-09-30 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_role'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0004_alter_orderofpayment_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_object_id', models.PositiveIntegerField()),
                ('uploaded_receipt', models.FileField(blank=True, null=True, upload_to='receipt/')),
                ('json_response', models.JSONField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('OTC', 'On the counter'), ('ONLINE', 'Online')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('related_object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['related_object_type', 'related_object_id'], name='payments_pa_related_1d6af5_idx'),
        ),
    ]
