# Generated by Django 4.1.7 on 2023-09-30 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_payment_payments_pa_related_1d6af5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.orderofpayment'),
            preserve_default=False,
        ),
    ]
