# Generated by Django 4.1.7 on 2023-09-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_payment_client_payment_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='uploaded_receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
