# Generated by Django 4.1.7 on 2023-10-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_cashier_options'),
        ('permits', '0036_remove_oritem_order_of_payment_delete_orderofpayment_and_more'),
        ('payments', '0008_payment_receipt_no_alter_payment_uploaded_receipt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderOfPayment',
            new_name='PaymentOrder',
        ),
    ]
