# Generated by Django 4.1.7 on 2023-10-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_cashier_options'),
        ('payments', '0009_rename_orderofpayment_paymentorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oritem',
            old_name='order_of_payment',
            new_name='payment_order',
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='prepared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_payment_orders', to='users.admin'),
        ),
    ]
