# Generated by Django 4.1.7 on 2023-10-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_rename_order_of_payment_oritem_payment_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oritem',
            options={'verbose_name': 'Payment Order Item'},
        ),
    ]
