# Generated by Django 4.1.7 on 2023-10-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_oritem_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ORItem',
            new_name='PaymentOrderItem',
        ),
    ]
