# Generated by Django 4.1.7 on 2023-10-07 13:59

from django.db import migrations, models
import users.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_paymentorder_permit_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[users.mixins.validate_amount]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uploaded_receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', validators=[users.mixins.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='paymentorderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[users.mixins.validate_amount]),
        ),
    ]
