# Generated by Django 4.1.7 on 2023-10-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_payment_amount_alter_payment_uploaded_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='approved_by',
        ),
    ]
