# Generated by Django 4.1.7 on 2023-10-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_remove_paymentorder_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
