# Generated by Django 4.1.7 on 2023-10-13 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_title'),
        ('payments', '0017_paymentorder_released_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
    ]
