# Generated by Django 4.1.7 on 2023-10-28 16:52

from django.db import migrations


def populate_created_by(apps, schema_editor):
    Cashier = apps.get_model('users', 'Cashier')
    Payment = apps.get_model('payments', 'Payment')

    previous_payments_with_no_cashier = Payment.objects.filter(
        created_by__isnull=True)
    cashier = Cashier.objects.first()

    for payment in previous_payments_with_no_cashier:
        payment.created_by = cashier
        payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_payment_created_at_payment_created_by'),
    ]

    operations = [
        migrations.RunPython(populate_created_by,
                             migrations.RunPython.noop),
    ]
