# Generated by Django 4.1.7 on 2023-12-04 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_user_title'),
        ('payments', '0024_alter_payment_uploaded_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='prepared_by',
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_payment_orders', to='users.admin'),
        ),
    ]
