# Generated by Django 4.1.7 on 2023-12-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_user_title'),
        ('payments', '0025_remove_paymentorder_prepared_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_payment_orders', to='users.signatory'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepared_payment_orders', to='users.signatory'),
        ),
    ]
