# Generated by Django 4.1.7 on 2023-12-05 02:06

from django.db import migrations


def null_all_created_by(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')

    for payment in Payment.objects.iterator():
        payment.created_by = None
        payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_paymentorder_approved_by_paymentorder_prepared_by'),
    ]

    operations = [
        migrations.RunPython(null_all_created_by,
                             migrations.RunPython.noop),
    ]
