# Generated by Django 4.1.7 on 2023-12-06 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_user_title'),
        ('payments', '0027_null_all_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_payments', to='users.cashier'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_payment_orders', to='users.signatory', verbose_name='Approval by'),
        ),
    ]
