# Generated by Django 4.1.7 on 2023-12-07 00:00

from django.db import migrations

from payments.models import PaymentType


def set_created_by_otc(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    Cashier = apps.get_model('users', 'Cashier')

    first_cashier = Cashier.objects.first()
    if first_cashier:
        otc_payments = Payment.objects.filter(
            payment_type=PaymentType.OTC)
        for payment in otc_payments.iterator():
            payment.created_by = first_cashier
            payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0028_alter_payment_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(set_created_by_otc,
                             migrations.RunPython.noop),
    ]
