# Generated by Django 4.1.7 on 2023-03-25 06:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_admin_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='new_field',
        ),
        migrations.AddField(
            model_name='client',
            name='agreed_to_terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='business_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=14, region=None, unique=True),
        ),
    ]
