# Generated by Django 4.1.7 on 2023-08-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_client_example_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='example_field',
        ),
    ]
