# Generated by Django 4.1.7 on 2023-08-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_registrationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationToken',
        ),
    ]
