# Generated by Django 4.1.7 on 2023-09-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_registrationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permittee',
            name='farm_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permittee',
            name='farm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='permittee',
            name='farm_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded-media/'),
        ),
        migrations.AlterField(
            model_name='permittee',
            name='permittee_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded-media/'),
        ),
    ]
