# Generated by Django 4.1.7 on 2023-09-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_cashier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashier',
            options={'verbose_name': 'Cashier'},
        ),
    ]
