# Generated by Django 4.1.7 on 2023-10-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_signatory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
