# Generated by Django 4.1.7 on 2023-10-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='business_name',
        ),
    ]
