# Generated by Django 4.1.7 on 2023-10-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0074_remove_permit_permittee'),
        ('users', '0021_remove_client_business_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permittee',
        ),
    ]
