# Generated by Django 4.1.7 on 2023-10-21 12:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_delete_permittee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='signs/'),
        ),
    ]
