# Generated by Django 4.1.7 on 2023-10-22 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validator',
            },
            bases=('users.user',),
            managers=[
                ('objects', users.models.ObjectManager()),
            ],
        ),
    ]
