# Generated by Django 4.1.7 on 2023-10-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
    ]
