# Generated by Django 4.1.7 on 2023-11-09 02:41

from django.db import migrations
import django_resized.forms
import users.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='signs/', validators=[users.mixins.validate_file_size, users.mixins.validate_file_extension]),
        ),
    ]
