# Generated by Django 4.1.7 on 2024-03-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_transientnotification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransientNotification',
            new_name='Notification',
        ),
    ]
