# Generated by Django 4.1.7 on 2023-08-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('FAUNA', 'Fauna'), ('FLORA', 'Flora')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SubSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
                ('main_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_species', to='animals.species')),
            ],
        ),
    ]
