# Generated by Django 4.1.7 on 2023-10-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subspecies',
            name='population',
        ),
    ]
