# Generated by Django 4.1.7 on 2023-10-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_remove_subspecies_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='subspecies',
            name='input_code',
            field=models.CharField(default='code', max_length=10),
            preserve_default=False,
        ),
    ]
