# Generated by Django 4.1.7 on 2023-10-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_subspecies_input_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subspecies',
            name='input_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
