# Generated by Django 4.1.7 on 2023-11-04 02:57

from django.db import migrations


def add_butterflies(apps, schema_editor):
    Species = apps.get_model('animals', 'Species')
    SubSpecies = apps.get_model('animals', 'SubSpecies')
    butterflies = [
        ('Appias albina', 'a al', 'Albatross White'),
        ('Appias lycinda andrea', 'al a', 'Albatross White'),
        ('Appias nero', 'a n', 'Dark Wanderer'),
        ('Atrophanuera semperi', 'a s', 'Philippine Batwing'),
        ('Attacus atlas', 'a at', 'Atlas Moth'),
        ('Attacus lorquini', 'a a', 'Pink Atlas Moth'),
        ('Catopsilia pomona', 'c p', 'Lemon Emigrant'),
        ('Catopsilia pyranthe', 'c py', 'Mottled Emigrant'),
        ('Catopsilia scylla', 'C S', 'Orange Emigrant'),
        ('Cepora aspasia', 'c as', 'common gull'),
        ('Cethosia biblis', 'c b', 'Red Lacewing'),
        ('Charaxes amycus', 'c am', 'Black Rajah'),
        ('Chilasa clytia palephates', 'c c', 'Common Mime'),
        ('Cynthia samia', 'c s', 'Samia Swallowtail'),
        ('Danaus affinis', 'd a', 'Malay Tiger'),
        ('Danaus chrysippus', 'd c', 'Plain Tiger'),
        ('Danaus genutia', 'd g', 'Striped Tiger'),
        ('Delias henningia', 'd h 1', 'Painted Jezebel'),
        ('Delias hyparete', 'd h 2', 'Painted Jezebel'),
        ('Doleschallia bisaltide', 'd b', 'Autumn Leaf'),
        ('Euploea mulciber', 'e m', 'Striped Blue Crow'),
        ('Euploea phaenareta', 'e p', 'King Crow'),
        ('Eurema hecabe', 'e h', 'Common Grass Yellow'),
        ('Graphium agamemnon', 'g a', 'Tailed Jay'),
        ('Graphium decolor', 'G dc', 'Common Jay'),
        ('Graphium doson', 'g d', 'Common Jay'),
        ('Graphium Euphrates', 'e g', 'Blue Jay'),
        ('Graphium Sarpedon', 'g s', 'Blue Jay'),
        ('Hebomoia glaucippe', 'h g', 'Great Orange Tip'),
        ('Hypolimnas bolina', 'h b', 'Great Eggfly'),
        ('Idea leuconoe', 'i l', 'Psyche'),
        ('Ideopsis juventa', 'i j', 'Malayan Wanderer'),
        ('Junonia almanac', 'j a', 'Peacock Pansy'),
        ('Junonia orithya', 'j o', 'Blue Pansy'),
        ('Lamproptera Meges', 'l m', 'Green Dragontail'),
        ('Pachiliopta kotzebuea', 'p k', 'Pink Rose'),
        ('Pachliopta antiphus', 'p an', 'Common Rose'),
        ('Pachliopta Aristolochiae', 'p a', 'Common Rose'),
        ('Papilio demoleus', 'p d', 'Lime Swallowtail'),
        ('Papilio helenus', 'p h', 'Red Helen'),
        ('Papilio lowi', 'p l', "Low's Swallowtail"),
        ('Papilio memnon', 'p m', 'Great Mormon'),
        ('Papilio palinurus', 'p p', 'Emerald Swallowtail'),
        ('Papilio polytes', 'p po', 'Common Mormon'),
        ('Papilio rumanzovia', 'p r', 'Scarlet Mormon'),
        ('Parantica vitrina', 'p v', 'Glassy Tiger'),
        ('Pareronia valeria', 'p va', 'Common Wanderer'),
        ('Parthenos sylvia', 'p s', 'Clipper'),
        ('Phalanta phalantha', 'p ph', 'Common Leopard'),
        ('Ptychandra lorquini', 'pty l', 'Common Jay'),
        ('Samia cynthia', 'S c', 'Ailanthus Silk moth'),
        ('Samia luzonica', 's l', 'Silk Moth'),
        ('Tirumata hamata', 't ha', 'Blue Tiger'),
        ('Troides rhadamantus', 't r', 'Golden Birdwing'),
        ('Vendula Erota', 'v e', 'White Dragontail'),
        ('Vindula dejone', 'v d', 'Cruiser')
    ]
    butterfly = Species.objects.filter(name__icontains='butterfly').first()

    for i in butterflies:
        scientific_name, input_code, common_name = i
        SubSpecies.objects.create(
            main_species=butterfly,
            input_code=input_code,
            scientific_name=scientific_name,
            common_name=common_name
        )


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_subspecies_input_code'),
    ]

    operations = [
        migrations.RunPython(add_butterflies,
                             migrations.RunPython.noop),
    ]
