# Generated by Django 4.1.7 on 2023-11-09 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_add_butterflies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='subspecies',
            options={'verbose_name': 'Sub Species', 'verbose_name_plural': 'Sub Species'},
        ),
    ]
