# Generated by Django 4.1.7 on 2023-11-25 13:30

from django.db import migrations
import django_resized.forms
import users.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_alter_species_options_alter_subspecies_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subspecies',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='subspecies/', validators=[users.mixins.validate_file_size]),
        ),
    ]
