# Generated by Django 4.1.7 on 2023-11-25 13:32

from django.db import migrations
import django_resized.forms
import users.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_subspecies_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subspecies',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='subspecies/', validators=[users.mixins.validate_image_only]),
        ),
    ]
