# Generated by Django 4.1.7 on 2023-08-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_no', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'On Draft'), ('SUBMITTED', 'Submitted'), ('RETURNED', 'Returned'), ('Accepted', 'Accepted'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired')], max_length=50)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
