# Generated by Django 4.1.7 on 2023-08-20 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeCollectorPermit',
            fields=[
                ('permit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permits.permit')),
            ],
            options={
                'verbose_name': "Wildlife Collector's Permit",
            },
            bases=('permits.permit',),
        ),
        migrations.CreateModel(
            name='WildlifeFarmPermit',
            fields=[
                ('permit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permits.permit')),
            ],
            options={
                'verbose_name': 'Wildlife Farm Permit',
            },
            bases=('permits.permit',),
        ),
        migrations.AddField(
            model_name='permit',
            name='validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='LocalTransportPermit',
            fields=[
                ('permit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permits.permit')),
                ('transport_location', models.CharField(max_length=255)),
                ('transport_date', models.DateField()),
                ('wcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wcp_ltps', to='permits.wildlifefarmpermit')),
                ('wfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfp_ltps', to='permits.wildlifefarmpermit')),
            ],
            options={
                'verbose_name': 'Local Transport Permit',
            },
            bases=('permits.permit',),
        ),
    ]
