# Generated by Django 4.1.7 on 2023-08-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0003_transportentry_permittedtocollectanimal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permit',
            old_name='validity',
            new_name='valid_until',
        ),
    ]
