# Generated by Django 4.1.7 on 2023-09-09 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_permittee_farm_address_and_more'),
        ('permits', '0004_rename_validity_permit_valid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('WFP', 'Wildlife Farm Permit'), ('WCP', 'Wildlife Collector Permit'), ('LTP', 'Local Transport Permit')], max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'On Draft'), ('SUBMITTED', 'Submitted'), ('RETURNED', 'Returned'), ('Accepted', 'Accepted'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_applications', to='users.client')),
            ],
        ),
        migrations.AddField(
            model_name='permit',
            name='client',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='users.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permit',
            name='permittee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporarily_assigned_permits', to='users.permittee'),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('REQUIREMENT_1', ' Requirement 1'), ('REQUIREMENT_2', ' Requirement 2')], max_length=50)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('permit_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.permitapplication')),
            ],
        ),
    ]
