# Generated by Django 4.1.7 on 2023-09-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0005_permitapplication_permit_client_permit_permittee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
