# Generated by Django 4.1.7 on 2023-09-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0006_permit_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permittedtocollectanimal',
            name='wcp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wcp_species', to='permits.wildlifecollectorpermit'),
        ),
    ]
