# Generated by Django 4.1.7 on 2023-09-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('permits', '0007_alter_permittedtocollectanimal_wcp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permittedtocollectanimal',
            unique_together={('sub_species', 'wcp')},
        ),
    ]
