# Generated by Django 4.1.7 on 2023-09-10 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_role'),
        ('permits', '0008_alter_permittedtocollectanimal_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='users.client'),
        ),
    ]
