# Generated by Django 4.1.7 on 2023-09-10 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0009_alter_permit_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permittedtocollectanimal',
            name='wcp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_species', to='permits.wildlifecollectorpermit'),
        ),
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('permit_application', 'requirement_type')},
        ),
    ]
