# Generated by Django 4.1.7 on 2023-09-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0010_alter_permittedtocollectanimal_wcp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='permit_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='permits.permitapplication'),
        ),
    ]
