# Generated by Django 4.1.7 on 2023-09-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0011_alter_requirement_permit_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.CharField(choices=[('REQUIREMENT_1', ' Requirement 1'), ('REQUIREMENT_2', ' Requirement 2'), ('REQUIREMENT_3', ' Requirement 3')], max_length=50),
        ),
    ]
