# Generated by Django 4.1.7 on 2023-09-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0013_permitapplication_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitapplication',
            name='transport_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permitapplication',
            name='permit_type',
            field=models.CharField(choices=[('WFP', 'Wildlife Farm Permit'), ('WCP', "Wildlife Collector's Permit"), ('LTP', 'Local Transport Permit')], max_length=50),
        ),
    ]
