# Generated by Django 4.1.7 on 2023-09-18 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0014_permitapplication_transport_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportentry',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_species_to_transport', to='permits.permitapplication'),
        ),
        migrations.AlterField(
            model_name='transportentry',
            name='ltp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_to_transport', to='permits.localtransportpermit'),
        ),
    ]
