# Generated by Django 4.1.7 on 2023-09-18 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0015_transportentry_application_alter_transportentry_ltp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportentry',
            old_name='application',
            new_name='permit_application',
        ),
    ]
