# Generated by Django 4.1.7 on 2023-09-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('permits', '0016_rename_application_transportentry_permit_application'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transportentry',
            unique_together={('sub_species', 'permit_application')},
        ),
    ]
