# Generated by Django 4.1.7 on 2023-09-20 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0018_alter_permitapplication_permit_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('WFP', 'Wildlife Farm Permit'), ('WCP', "Wildlife Collector's Permit"), ('LTP', 'Local Transport Permit'), ('CWR', 'Certificate of Wildlife Registration'), ('GP', 'Gratuitous Permit')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(choices=[('PRIOR_CLEARANCE_FROM_AFFECTED_COMMUNITIES', 'Prior clearance from the affected communities, i.e. concerned LGUs, recognized head people in accordance with R.A. 8371, or PAMB'), ('CERT_OF_REGISTRATION', 'Copy of Certificate of Registration from appropriate Government agencies'), ('SCIENTIFIC_EXPERTISE_PROOF', 'Proof of scientific expertise (list of qualifications of manpower)'), ('FINANCIAL_PLAN', 'Financial plan showing financial capability to go into breeding'), ('PROPOSED_FACILITY_DESIGN', 'Proposed facility design'), ('LETTER_OF_COMMITMENT', 'In case of indigenous threatened species, letter of commitment to simultaneously undertake conservation breeding and propose measures on rehabilitation and/or protection of habitat, where appropriate, as may be determined by the RWMC'), ('CITIZENSHIP', 'Citizenship verification papers, if citizenship is by Naturalization'), ('DOCUMENTS_SUPPORTING_LEGAL_POSSESSION_OF_WILDLIFE', 'Documents supporting the legal possession/ acquisition of wildlife'), ('PHYTOSANITARY_OR_VETERINARY_CERT', 'Phytosanitary Certificate (for plants) or Veterinary Quarantine Certificate (for animals) from the concerned Department of Agriculture (DA) Office.')], max_length=1000, unique=True)),
                ('optional', models.BooleanField(default=False)),
                ('requirement_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='permits.requirementlist')),
            ],
            options={
                'unique_together': {('requirement_list', 'requirement')},
            },
        ),
    ]
