# Generated by Django 4.1.7 on 2023-09-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0019_requirementlist_requirementitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requirementitem',
            unique_together=set(),
        ),
    ]
