# Generated by Django 4.1.7 on 2023-09-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0021_alter_requirementitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementlist',
            name='permit_type',
            field=models.CharField(choices=[('WFP', 'Wildlife Farm Permit'), ('WCP', "Wildlife Collector's Permit"), ('LTP', 'Local Transport Permit'), ('CWR', 'Certificate of Wildlife Registration'), ('GP', 'Gratuitous Permit')], max_length=50),
        ),
    ]
