# Generated by Django 4.1.7 on 2023-09-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0022_alter_requirementlist_permit_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requirementitem',
            unique_together=set(),
        ),
    ]
