# Generated by Django 4.1.7 on 2023-09-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0024_alter_requirementitem_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitapplication',
            name='names_and_addresses_of_authorized_collectors_or_trappers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
