# Generated by Django 4.1.7 on 2023-09-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0026_collectionentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionentry',
            name='permit_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_species', to='permits.permitapplication'),
        ),
    ]
