# Generated by Django 4.1.7 on 2023-09-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0029_alter_requirement_requirement_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('permit_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permits.permitapplication')),
            ],
        ),
    ]
