# Generated by Django 4.1.7 on 2023-09-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0030_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='remarks',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
