# Generated by Django 4.1.7 on 2023-09-25 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0031_remarks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remarks',
            name='permit_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='permits.permitapplication'),
        ),
    ]
