# Generated by Django 4.1.7 on 2023-09-25 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permits', '0032_alter_remarks_permit_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remarks',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='remarks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
