# Generated by Django 4.1.7 on 2023-10-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0039_add_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementitem',
            name='requirement_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='permits.requirement'),
            preserve_default=False,
        ),
    ]
