# Generated by Django 4.1.7 on 2023-10-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0040_requirementitem_requirement_fk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requirementitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='requirementitem',
            name='requirement',
        ),
    ]
