# Generated by Django 4.1.7 on 2023-10-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0041_alter_requirementitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirementitem',
            old_name='requirement_fk',
            new_name='requirement',
        ),
    ]
