# Generated by Django 4.1.7 on 2023-10-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0043_alter_requirementitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uploadedrequirement',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='uploadedrequirement',
            name='uploaded_file',
            field=models.FileField(upload_to='requirements/'),
        ),
    ]
