# Generated by Django 4.1.7 on 2023-10-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0045_uploadedrequirement_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedrequirement',
            name='requirement_type',
        ),
    ]
