# Generated by Django 4.1.7 on 2023-10-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0046_remove_uploadedrequirement_requirement_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uploadedrequirement',
            unique_together={('permit_application', 'requirement')},
        ),
    ]
