# Generated by Django 4.1.7 on 2023-10-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_cashier_options'),
        ('permits', '0047_alter_uploadedrequirement_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='inspection_reports/')),
                ('inspecting_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.admin')),
                ('permit_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='permits.permitapplication')),
            ],
        ),
    ]
