# Generated by Django 4.1.7 on 2023-10-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_cashier_options'),
        ('permits', '0048_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspecting_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
