# Generated by Django 4.1.7 on 2023-10-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0049_alter_inspection_inspecting_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitapplication',
            name='transport_location',
            field=models.CharField(default='Gasan', max_length=255),
            preserve_default=False,
        ),
    ]
