# Generated by Django 4.1.7 on 2023-10-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0050_permitapplication_transport_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtransportpermit',
            name='transport_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='permitapplication',
            name='transport_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
