# Generated by Django 4.1.7 on 2023-10-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0051_alter_localtransportpermit_transport_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtransportpermit',
            name='transport_location',
            field=models.CharField(max_length=255),
        ),
    ]
