# Generated by Django 4.1.7 on 2023-10-03 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0052_alter_localtransportpermit_transport_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitapplication',
            name='permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permits.permit'),
        ),
    ]
