# Generated by Django 4.1.7 on 2023-10-03 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0053_permitapplication_permit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtransportpermit',
            name='wcp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wcp_ltps', to='permits.wildlifecollectorpermit'),
        ),
    ]
