# Generated by Django 4.1.7 on 2023-10-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_paymentorder_permit_application'),
        ('permits', '0057_transportentry_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='payment_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentorder'),
        ),
    ]
