# Generated by Django 4.1.7 on 2023-10-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0058_permit_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitapplication',
            name='permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permits.permit'),
        ),
    ]
