# Generated by Django 4.1.7 on 2023-10-07 13:59

from django.db import migrations, models
import users.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0062_permit_inspection_alter_permit_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='inspection_reports/', validators=[users.mixins.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_no',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[users.mixins.validate_file_extension]),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['content_type', 'object_id'], name='permits_sig_content_b6bc99_idx'),
        ),
    ]
