# Generated by Django 4.1.7 on 2023-10-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0063_inspection_no_alter_inspection_report_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='permit_application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='permits.permitapplication'),
        ),
    ]
