# Generated by Django 4.1.7 on 2023-10-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0064_alter_inspection_permit_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='no',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='permit_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permits.permitapplication'),
        ),
    ]
