# Generated by Django 4.1.7 on 2023-10-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_signatory'),
        ('permits', '0065_alter_inspection_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='permittee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporarily_assigned_permits', to='users.permittee', verbose_name='Permittee (unregistered client)'),
        ),
    ]
