# Generated by Django 4.1.7 on 2023-10-09 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_payment_amount_alter_payment_uploaded_receipt_and_more'),
        ('permits', '0068_alter_permit_inspection_alter_permit_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permits.inspection'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='payment_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentorder'),
        ),
    ]
