# Generated by Django 4.1.7 on 2023-10-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0069_alter_permit_inspection_alter_permit_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='issued_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
