# Generated by Django 4.1.7 on 2023-10-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0070_permit_issued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='issued_date',
            field=models.DateField(null=True),
        ),
    ]
