# Generated by Django 4.1.7 on 2023-10-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0071_alter_permit_issued_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='or_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
