# Generated by Django 4.1.7 on 2023-10-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0072_permit_or_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='or_no',
            field=models.CharField(max_length=100, null=True, verbose_name='Order No.'),
        ),
    ]
