# Generated by Django 4.1.7 on 2023-10-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0073_alter_permit_or_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permit',
            name='permittee',
        ),
    ]
