# Generated by Django 4.1.7 on 2023-10-20 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_subspecies_input_code'),
        ('permits', '0076_alter_transportentry_sub_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionentry',
            name='sub_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='animals.subspecies', verbose_name='Species'),
        ),
    ]
