# Generated by Django 4.1.7 on 2023-10-21 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_alter_paymentorder_client'),
        ('permits', '0077_alter_collectionentry_sub_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='payment_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentorder'),
        ),
    ]
