# Generated by Django 4.1.7 on 2023-10-21 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0079_alter_permit_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionentry',
            name='wcp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowed_animals', to='permits.wildlifecollectorpermit'),
        ),
    ]
