# Generated by Django 4.1.7 on 2023-10-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0081_remove_collectionentry_wcp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='image',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='title',
        ),
    ]
