# Generated by Django 4.1.7 on 2023-10-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0082_remove_signature_image_remove_signature_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'On Draft'), ('SUBMITTED', 'Submitted'), ('RETURNED', 'Returned'), ('ACCEPTED', 'Accepted'), ('RELEASED', 'Released'), ('USED', 'Used'), ('EXPIRED', 'Expired')], max_length=50),
        ),
        migrations.AlterField(
            model_name='permitapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'On Draft'), ('SUBMITTED', 'Submitted'), ('RETURNED', 'Returned'), ('ACCEPTED', 'Accepted'), ('RELEASED', 'Released'), ('USED', 'Used'), ('EXPIRED', 'Expired')], max_length=50),
        ),
    ]
