# Generated by Django 4.1.7 on 2023-10-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0086_remove_inspection_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='farm_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='farm_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
