# Generated by Django 4.1.7 on 2023-10-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0088_permitapplication_farm_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitapplication',
            name='farm_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='permitapplication',
            name='farm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
