# Generated by Django 4.1.7 on 2023-10-29 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_validator'),
        ('permits', '0090_alter_collectionentry_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspecting_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='no',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='permit_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='permits.permitapplication'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='scheduled_date',
            field=models.DateField(),
        ),
    ]
