# Generated by Django 4.1.7 on 2023-10-29 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_validator'),
        ('permits', '0091_alter_inspection_inspecting_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspecting_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='scheduled_date',
            field=models.DateField(null=True),
        ),
    ]
