# Generated by Django 4.1.7 on 2023-11-01 15:48

from django.db import migrations, models
import users.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0093_alter_inspection_permit_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='or_no_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[users.mixins.validate_amount]),
        ),
    ]
