# Generated by Django 4.1.7 on 2023-11-09 02:41

from django.db import migrations, models
import users.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0095_alter_permit_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='uploaded_file',
            field=models.FileField(null=True, upload_to='uploads/', validators=[users.mixins.validate_file_extension, users.mixins.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='uploadedrequirement',
            name='uploaded_file',
            field=models.FileField(upload_to='requirements/', validators=[users.mixins.validate_file_size]),
        ),
    ]
