# Generated by Django 4.1.7 on 2023-11-25 12:40

from django.db import migrations, models
import users.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0096_alter_permit_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='example_file',
            field=models.FileField(blank=True, null=True, upload_to='example-requirements/', validators=[users.mixins.validate_file_size]),
        ),
    ]
