# Generated by Django 4.1.7 on 2023-11-26 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0097_requirement_example_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorOrTrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('permit_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectors_or_trappers', to='permits.permitapplication')),
            ],
        ),
    ]
