# Generated by Django 4.1.7 on 2023-11-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0098_collectorortrapper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitapplication',
            name='names_and_addresses_of_authorized_collectors_or_trappers',
        ),
    ]
