# Generated by Django 4.1.7 on 2023-12-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_user_title'),
        ('permits', '0099_remove_permitapplication_names_and_addresses_of_authorized_collectors_or_trappers'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitapplication',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_applications', to='users.admin'),
        ),
    ]
