# Generated by Django 4.1.7 on 2023-12-07 01:45

from django.db import migrations, models
import users.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0100_permitapplication_accepted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitapplication',
            name='inspection_report',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_inspections/', validators=[users.mixins.validate_file_size]),
        ),
    ]
