# Generated by Django 4.1.7 on 2023-12-07 01:45

from django.db import migrations, models
import users.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0101_permitapplication_inspection_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitapplication',
            name='inspection_report',
            field=models.FileField(null=True, upload_to='uploaded_inspections/', validators=[users.mixins.validate_file_size]),
        ),
    ]
